"""make creator field unallable

Revision ID: 349cbc07224a
Revises: c101f1d92738
Create Date: 2026-01-15 16:38:22.876322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349cbc07224a'
down_revision: Union[str, Sequence[str], None] = 'c101f1d92738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'creator_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('folders', 'creator_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('folders', 'creator_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('applications', 'creator_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
